# Generated by Django 6.0.7 on 2026-07-15 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_filename', models.CharField(max_length=255)),
                ('extracted_profile', models.JSONField(default=dict, help_text='Structured profile extracted from resume (skills, experience, etc.)')),
                ('platforms_used', models.JSONField(default=list, help_text='List of platforms searched, e.g. ["simplyhired", "indeed"]')),
                ('credits_used', models.IntegerField(default=0)),
                ('jobs_found', models.IntegerField(default=0)),
                ('matched_jobs', models.JSONField(default=list, help_text='Array of matched job objects with scores')),
                ('csv_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
